var policies = {
    813: "Abortion, Embryology and Euthanasia- Against",
	6690: "Abusive Tax Avoidance Should be Illegal",
	6687: "Academy Schools - for",
	6681: "Additional Rate of Income Tax - Increase",
	1034: "Ban fox hunting",
	6685: "Bankers' Bonus Tax",
	1016: "Business and community control of schools: For",
	1120: "Cap or Reduce Civil Service Redundancy Payments",
	794: "Civil aviation pollution - For limiting",
	6715: "Closed Material Proceedure",
	6667: "Coalition Programme for Government - For",
	981: "Control Orders",
	839: "Corporal punishment of children - Against",
	827: "Crossrail - In favour",
	6710: "Cull Badgers",
	1115: "Deployment of UK armed forces in Afghanistan",
	6716: "Employee Shareholder Status",
	6682: "End support for some 16-18 yr olds in education",
	6689: "Energy Prices - More Affordable",
	1113: "Equal Number of Electors Per Constituency - for",
	1065: "European Union - For",
	6672: "Excess Bedroom Benefit Penalty for Social Tenants",
	6698: "Fixed Term Parliaments",
	363: "Foundation hospitals - In favour",
	1050: "Fox hunting - Ban",
	1008: "Freedom of Information Bill 2000 - Strengthen",
	837: "Fully Elected House of Lords",
	6709: "Further Devolution to Scotland",
	6708: "Further devolution to Wales",
	810: "Gambling - Against permissiveness",
	6676: "GP Commissioning in the NHS",
	6694: "Higher taxes on alcoholic drinks",
	1014: "Hold a UK referendum on Lisbon EU Treaty",
	826: "Homosexuality - Equal rights",
	6703: "Human Rights and Equality",
	1051: "Identity cards - For introduction",
	6704: "Incentivise Low Carbon Electricity Generation",
	6699: "Increase Air Passenger Duty",
	6680: "Increase the income tax - tax free allowance",
	1110: "Increase VAT",
	1049: "Iraq 2003 - For the invasion",
	975: "Iraq Investigation - Necessary",
	6702: "Jobs Guarantee for Long Term Young Unemployed",
	6677: "Limit NHS Foundation Trust Private Patient Income",
	6684: "Localise Council Tax Support",
	6693: "Lower taxes on petrol &amp; diesel for motor vehicles",
	6711: "Mansion Tax",
	6721: "Mass Retention of Communications Data",
	1071: "Ministers Can Intervene in Coroners' Inquests",
	6673: "More Generous Benefits for Ill and Disabled",
	6695: "More powers for local councils",
	1039: "No detention without charge or trial",
	1119: "No Polls Clash With MP Election System Referendum",
	852: "Nuclear power - For",
	856: "Parliamentary scrutiny - Reduce",
	1124: "Pension auto-enrolment - For",
	6696: "Police and Crime Commissioners",
	1012: "Post office - in favour of Government policy",
	1032: "Post office closures - against",
	6712: "Prevent abuse of zero hours contracts",
	1105: "Privatise Royal Mail",
	1109: "Promote Occupational Pensions",
	1084: "Proportional Representation Voting System - For ",
	629: "Protesting near Parliament - Unrestricted",
	6692: "Rail Fares - Lower",
	812: "Recreational drugs - Against legalization",
	6670: "Reduce Spending on Welfare Benefits",
	6671: "Reduce spending power of local government",
	6679: "Reduce the rate of Corporation Tax",
	1136: "Reducing the number of MPs - for",
	1112: "Referendum on Alternative Vote for MP Elections",
	1027: "Referendum on the UK's membership of the EU - For",
	6717: "Referendums for Directly Elected City Mayors",
	6720: "Register of Lobbyists",
	1079: "Remove Hereditary Peers from the House of Lords",
	6705: "Require Pub Companies to Offer Rent Only Leases",
	6678: "Restrict 3rd party campaigners during elections",
	6707: "Restrict Scope of Legal Aid",
	6683: "Retention of Business Rates by Local Government",
	1021: "Right to strike",
	6686: "Same Sex Marriage - for",
	1074: "Schools - Greater Autonomy",
	6697: "Sell England's Public Forests",
	811: "Smoking ban - In favour",
	1030: "Stop climate change",
	6706: "Stronger Military Covenant",
	6691: "Tax Incentives for Companies Investing in Assets",
	1041: "Termination of pregnancy - against",
	1053: "Terrorism laws - For",
	1015: "The UK should not ratify the Lisbon Treaty",
	809: "Transexuality - Against legal recognition",
	996: "Transparency of Parliament",
	984: "Trident replacement - In favour",
	1132: "Tuition fees - Set Upper Limit at £9,000 per Year",
	367: "University education fees - Should be free",
	1052: "University Tuition Fees - For",
	6688: "Use of UK Military Forces Overseas",
	842: "Voting age - Reduce to 16",
	995: "War - Parliamentary authority not necessary",
	6674: "Welfare benefits ought rise in line with prices"
}